### ISSUE TITLE
Cookies do not appear in browser storage

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [Mahdrentys/wasm-cookies-rs#8]
Hi,

I tried setting a cookie in a yew application but the browser (firefox) does not show the cookie being set in its cache. Among other things I tried this snippet which I took from your tests:
```
        wasm_cookies::cookies::set_raw(
            "key",
            "value",
            &CookieOptions::default().expires_at_timestamp(1100000000000),
        );
```
What am I doing wrong? 🤔

**Comment by HerrMuellerluedenscheid** [comment]
In case others stumble accross the same: I was mislead by the namespaces and didn't realize that I was importing the wrong methods. Methods  inside `wasm_cookies::cookies` don't set cookies an documents. They create properly encoded or raw cookie setting strings. How about rename `cookies::set` to something like `cookies::create_cookie_string` or something?
Also, as the methods such as `wasm_cookies::set` are nicely gated by a `cfg(wasm)` flag they are not considered at least by my IDE (which I think is a flaw of the IDE). So, watch out that you import and use the right thing.

**Comment by Mahdrentys** [comment]
The documentation makes it quite clear that methods in the `cookies` module don't actually affect the browser's cookie string, so I don't think renaming the functions is necessary.

About the `cfg(wasm)` attribute on the functions at the root of the crate, I'm not sure what the consensus is about using it or not (panicking in the latter case) for wasm crates. I will look into it. In any case, you can change the cargo target to a wasm one on the rust-analyzer extension on vscode.

**Comment by EvoTeamDevelop** [comment]
I agree with @HerrMuellerluedenscheid as it is not transparent that cookies::set is not creating a cookie, but a string and you need to use a different namespace with the same method name. It is really confusing.
